# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_auto_20170813_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
