# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0004_auto_20170816_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessurl',
            name='shortcode',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
