# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import src.apps.shorter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessurl',
            name='shortcode',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='lessurl',
            name='url',
            field=models.CharField(max_length=220, validators=[src.apps.shorter.validators.validate_url]),
        ),
    ]
