# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import src.apps.shorter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_auto_20171119_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessurl',
            name='url',
            field=models.CharField(max_length=220, unique=True, validators=[src.apps.shorter.validators.validate_url]),
        ),
    ]
