---

#- name: restart site
#  supervisorctl: name={{ project_url }} state=restarted

#- name: restart mysql
#  service: name=mysql state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart ssh
  service: name=sshd state=restarted enabled=yes

- name: restart emperator
  service: name:shortner state=restarted enabled=yes
